<a href="https://colab.research.google.com/github/0723pm/HW/blob/master/%D0%B4%D0%B7_%D1%81%D0%B5%D0%BC%D0%B8%D0%BD%D0%B0%D1%803.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Задача 1

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [29]:
import pandas as pd
path ="/content/drive/MyDrive/kc_house_data.csv"
df = pd.read_csv(path)
df.describe

<bound method NDFrame.describe of                id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00
1      6414100192  20141209T000000  538000.0         3       2.25
2      5631500400  20150225T000000  180000.0         2       1.00
3      2487200875  20141209T000000  604000.0         4       3.00
4      1954400510  20150218T000000  510000.0         3       2.00
...           ...              ...       ...       ...        ...
21608   263000018  20140521T000000  360000.0         3       2.50
21609  6600060120  20150223T000000  400000.0         4       2.50
21610  1523300141  20140623T000000  402101.0         2       0.75
21611   291310100  20150116T000000  400000.0         3       2.50
21612  1523300157  20141015T000000  325000.0         2       0.75

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7
1             2570      7242     2.0           0     0  ...      7
2              770     10000     1.0           0     0  ...      6
3             1960      5000     1.0           0     0  ...      7
4             1680      8080     1.0           0     0  ...      8
...            ...       ...     ...         ...   ...  ...    ...
21608         1530      1131     3.0           0     0  ...      8
21609         2310      5813     2.0           0     0  ...      8
21610         1020      1350     2.0           0     0  ...      7
21611         1600      2388     2.0           0     0  ...      8
21612         1020      1076     2.0           0     0  ...      7

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112
1            2170            400      1951          1991    98125  47.7210
2             770              0      1933             0    98028  47.7379
3            1050            910      1965             0    98136  47.5208
4            1680              0      1987             0    98074  47.6168
...           ...            ...       ...           ...      ...      ...
21608        1530              0      2009             0    98103  47.6993
21609        2310              0      2014             0    98146  47.5107
21610        1020              0      2009             0    98144  47.5944
21611        1600              0      2004             0    98027  47.5345
21612        1020              0      2008             0    98144  47.5941

          long  sqft_living15  sqft_lot15
0     -122.257           1340        5650
1     -122.319           1690        7639
2     -122.233           2720        8062
3     -122.393           1360        5000
4     -122.045           1800        7503
...        ...            ...         ...
21608 -122.346           1530        1509
21609 -122.362           1830        7200
21610 -122.299           1020        2007
21611 -122.069           1410        1287
21612 -122.299           1020        1357

[21613 rows x 21 columns]>

1.2. Создать новый признак delta_renovated, который будет содержать разницу в годах между годом реновацией дома и годом постройки дома
Если реновации дома не было, то в новом признаке поставьте 0.

In [4]:
df['delta_renovated'] = 0
df.loc[df['yr_renovated'] != 0, 'delta_renovated'] = df['yr_renovated'] - df['yr_built']
df.delta_renovated.sort_values()

0          0
14285      0
14284      0
14283      0
14282      0
        ...
586      110
6671     113
2566     114
15046    114
11695    114
Name: delta_renovated, Length: 21613, dtype: int64

1.3 Создайте признаки года продажи, месяца продажи

In [16]:

def col_split(x):
  return x.split(' ')[0]

df['year_sale'] = df['year_of_sale'].apply(col_split)
df.head

AttributeError: ignored

1.4 Удалите признаки date, zipcode, lat, long

In [9]:
df.drop(columns=['date', 'zipcode', 'lat', 'long'], inplace=True)
df.head()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,...,sqft_above,sqft_basement,yr_built,yr_renovated,sqft_living15,sqft_lot15,price_specific_area,delta_renovated,year_of_sale,month_of_sale
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,3,...,1180,0,1955,0,1340,5650,39.274336,0,2014,10
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,3,...,2170,400,1951,1991,1690,7639,74.288870,40,2014,12
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,3,...,770,0,1933,0,2720,8062,18.000000,0,2015,2
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,5,...,1050,910,1965,0,1360,5000,120.800000,0,2014,12
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,3,...,1680,0,1987,0,1800,7503,63.118812,0,2015,2

## Задача 2

Создайте датафрейм с клиентами:

In [28]:
clients = pd.DataFrame({
'client_id': [1459, 4684, 3498, 3942, 4535, 2308, 2866, 2765, 1472, 4236, 2295,
939, 3840, 280, 20, 4332, 3475, 4213, 3113, 4809, 2134, 2242,
2068, 4929, 1384, 1589, 3317, 2260, 1727, 1764, 1611, 1474],
'house_id': [8965450190, 6823100225, 5104540330, 2131701075, 1522700060,
1189000207, 6821600300, 7137950720, 9510920050, 6131600255,
5428000070, 1788800910, 8100400160, 3123049142, 6306800010,
5083000375, 7920100025, 1951600150, 809001400, 339600110,
1622049154, 1099600250, 8563000110, 2768100205, 3995700435,
8861700030, 3303980210, 7731100066, 8146100580, 825069097,
3889100029, 9524100196]
})
clients_id = clients.set_index('house_id')
clients_id.head()

            client_id
house_id
8965450190       1459
6823100225       4684
5104540330       3498
2131701075       3942
1522700060       4535

2.1 Присоедините к таблице clients данные по домам через метод join

In [30]:
id_house = df.set_index('id')
id_house = df.set_index('id')

joined = clients_id.join(id_house)
joined.head()

,client_id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
339600110,4809,20140923T000000,395000.0,3,2.50,1610,3755,2.0,0,0,...,7,1610,0,1987,0,98052,47.6825,-122.097,1300,3823
809001400,3113,20140922T000000,925000.0,3,1.00,1630,3200,1.5,0,0,...,8,1630,0,1912,0,98109,47.6351,-122.352,1710,3600
825069097,1764,20140619T000000,770000.0,3,2.50,2650,40705,2.0,0,0,...,9,2650,0,1994,0,98053,47.6680,-122.063,2550,42625
1099600250,2242,20141202T000000,260000.0,3,1.75,1710,6400,1.0,0,0,...,7,1240,470,1976,0,98023,47.3036,-122.377,1600,6400
1189000207,2308,20141021T000000,387000.0,2,2.50,1170,1394,2.0,0,0,...,8,1170,0,2001,0,98122,47.6131,-122.297,1250,3136

2.2 Присоедините к таблице clients данные по домам через метод merge
Это нужно, чтобы понимать, какие дома покупались клиентами
house_id - это индексы датафрейма с домами

In [31]:
merged = clients.merge(df, left_on = 'house_id', right_on = 'id')
merged.head()

,client_id,house_id,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1459,8965450190,8965450190,20150218T000000,295000.0,3,2.50,1500,3060,2.0,...,7,1500,0,1994,0,98006,47.5605,-122.117,2700,7734
1,4684,6823100225,6823100225,20150414T000000,700000.0,4,1.75,1870,6000,1.0,...,8,1670,200,1949,0,98199,47.6435,-122.399,1710,6000
2,3498,5104540330,5104540330,20150508T000000,679000.0,4,2.50,3680,7236,2.0,...,10,3680,0,2006,0,98038,47.3543,-122.005,3310,7180
3,3942,2131701075,2131701075,20141204T000000,420000.0,3,1.75,1720,5000,1.5,...,8,1720,0,1932,2009,98019,47.7380,-121.983,1410,8300
4,4535,1522700060,1522700060,20140624T000000,518000.0,4,2.75,2520,14021,2.0,...,9,2520,0,1999,0,98019,47.7344,-121.957,2330,14007